@startwbs ゆで卵を食べる
* ゆで卵を食べる

**[#Aqua] 卵を買う
***[#Yellow] 銀行で金をおろす
***[#Yellow] スーパーで卵を買う

**[#Aqua] ゆで卵を作る
***[#Yellow] 卵を洗う
***[#Yellow] お湯を沸かす
***[#Yellow] 卵をゆでる

**[#Aqua] 食べる準備をする
***[#Yellow] 腹筋して腹をへらす
***[#Yellow] 殻を割る
***[#Yellow] 塩を振る
@endwbs
